device: "cpu" # cuda:0, cpu
dt: 0.1 # 0.05, 0.1
steps: 1000
sim_model: "dynamic"      # kinematic, dynamic, SVGP, SVGP_wet
mppi_model: "dynamic"     # kinematic, dynamic, SVGP
v_target: 3.5            # 1.5 2.5, 4.0, 5.0
laps: 1                   # number of laps to log
disturbance: 0            # 0: disturbance off, 1: disturbance on
track: "racetrack_vicon_2"    # "racetrack_vicon_2" , "racetrack_vicon" , "simple_smooth", "simple_smooth_small", "straight_line", "simple_smooth_flip", "racetrack_vicon_short"
viz_rollouts: 0           # 0: don't visualize the rollouts, 1: visualize the rollouts
use_obstacle: "off"           # "static", "dynamic", "off", "agent"
vel_mode: "gt"            # velocity estimation technique, ls, fd, gt: ground truth from simulator
env: "sim"                # "lab" , "sim" -- used for resetting the sim or not
troubleshoot: 0           # 0: off, 1: on - display distribution of rollouts


throttle_min: 0.0
throttle_max: 1.0 # 0.6
steering_min: -1.0 # -0.8
steering_max: 1.0 # 0.8

mode: "FM_mppi"              # "mppi", "s_mppi", "s_mppi_dyn_lim", "FM_mppi" (Fused-Mean MPPI)

mppi:
  update_cov: False
  pre_filter: "lowpass" # "off", "lowpass"
  eta_u_bound: 180 # 280, 300 1100
  eta_l_bound: 5.0 # 2.5 200
  device: "cpu" # cuda:0, cpu
  mppi_mode: "simple"  # halton-spline, simple
  sampling_method: "random"   # halton, random
  num_samples: 4000 # 50 # 100 50 4000 # 100
  horizon: 10 # 12, 15, 20                 # At least 12 for Halton Sampling
  u_per_command: 10               # Make same as horizon so control over entire horizon gets outputted
  rollout_var_discount: 0.95 # 0.95 # 0.95 # 0.95
  sample_null_action: True
  noise_abs_cost: False
  filter_u: False
  use_priors: False
  update_lambda: False
  lambda_: 0.05 # 0.05, 0.5, 40
# MPPI
  u_min: [0.0, -1.0]
  u_max: [1.0, 1.0]
  noise_sigma:  [[0.3, 0.0], [0.0, 0.5]] # [[0.1, 0.0], [0., 0.2]] , [[0.3, 0.0], [0., 0.5]]

# S-MPPI
#  u_min: [-0.5, -3.0] # 0.5, 2.0
#  u_max: [0.5, 3.0]
#  noise_sigma: [[0.2, 0.0], [0., 1.0]] # 0.2, 0.8





